/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course;

/**
 *
 * @author wizard
 */
public class MainPanel extends java.awt.Panel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        choice1 = new java.awt.Choice();
        textArea1 = new java.awt.TextArea();
        cbAgree = new java.awt.Checkbox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setLabel("button1");
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        button2.setLabel("button2");
        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 130, -1));
        add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, 110));

        cbAgree.setLabel("checkbox1");
        add(cbAgree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    protected java.awt.Checkbox cbAgree;
    private java.awt.Choice choice1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
